import hashlib
import json
import sqlite3
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path


@dataclass
class SystemSummary:
    system: str
    file_count: int
    files: list[dict]


@dataclass
class DangerRecord:
    id: str
    scope: str
    description: str
    reason: str | None


@dataclass
class DecisionRecord:
    id: str
    scope: str | None
    decision: str
    alternatives: str | None
    reason: str | None
    added_by: str


@dataclass
class ChangeRecord:
    file: str
    commit_hash: str | None
    summary: str | None
    author: str | None
    timestamp: str | None


@dataclass
class SessionEntry:
    entry: str
    files_touched: str | None
    timestamp: str | None


@dataclass
class IndexStats:
    file_count: int
    function_count: int
    stale_count: int
    tainted_count: int


@dataclass
class ProjectSnapshot:
    repo_name: str
    systems: list[SystemSummary]
    global_dangers: list
    file_dangers: list
    decisions: list
    recent_changes: list
    session_log: list
    stats: IndexStats


GENERATED_HEADER = "<!-- AUTO-GENERATED BY ctx -- DO NOT EDIT MANUALLY -->"
TIMESTAMP_LINE = "<!-- Generated: {ts} -->"


def _now_ts() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def extract_project_snapshot(
    conn: sqlite3.Connection,
    repo_root: Path,
) -> ProjectSnapshot:
    repo_name = repo_root.name

    file_rows = conn.execute(
        "SELECT path, system, purpose, summary FROM files ORDER BY system, path"
    ).fetchall()

    systems_dict = defaultdict(list)
    for row in file_rows:
        system = row["system"] or "uncategorized"
        systems_dict[system].append({
            "path": row["path"],
            "purpose": row["purpose"] or row["summary"] or "(not yet summarized)",
        })

    systems = [
        SystemSummary(
            system=system,
            file_count=len(files),
            files=files,
        )
        for system, files in sorted(systems_dict.items())
    ]

    global_dangers = conn.execute(
        "SELECT id, scope, description, reason, added_by FROM dangers "
        "WHERE scope = '*' ORDER BY added_by DESC, rowid"
    ).fetchall()

    file_dangers = conn.execute(
        "SELECT id, scope, description, reason, added_by FROM dangers "
        "WHERE scope != '*' ORDER BY scope, added_by DESC"
    ).fetchall()

    decisions = conn.execute(
        "SELECT id, scope, decision, alternatives, reason, added_by FROM decisions "
        "ORDER BY added_by DESC, scope NULLS LAST, rowid"
    ).fetchall()

    recent_changes = conn.execute(
        "SELECT file, commit_hash, summary, author, timestamp FROM changes "
        "ORDER BY timestamp DESC LIMIT 5"
    ).fetchall()

    session_log = conn.execute(
        "SELECT entry, files_touched, timestamp FROM session_log "
        "ORDER BY timestamp DESC LIMIT 1"
    ).fetchall()

    stats = IndexStats(
        file_count=conn.execute("SELECT COUNT(*) FROM files").fetchone()[0],
        function_count=conn.execute("SELECT COUNT(*) FROM functions").fetchone()[0],
        stale_count=conn.execute(
            "SELECT COUNT(*) FROM files WHERE is_stale = 1"
        ).fetchone()[0],
        tainted_count=conn.execute(
            "SELECT COUNT(*) FROM functions WHERE is_tainted = 1"
        ).fetchone()[0],
    )

    return ProjectSnapshot(
        repo_name=repo_name,
        systems=systems,
        global_dangers=list(global_dangers),
        file_dangers=list(file_dangers),
        decisions=list(decisions),
        recent_changes=list(recent_changes),
        session_log=list(session_log),
        stats=stats,
    )


def render_claude_md(snapshot: ProjectSnapshot, gen_ts: str | None = None) -> str:
    ts = gen_ts or _now_ts()
    lines = [
        GENERATED_HEADER,
        TIMESTAMP_LINE.format(ts=ts),
        "",
        f"# {snapshot.repo_name}",
        "",
    ]

    if snapshot.session_log:
        entry = snapshot.session_log[0]
        lines.append("## Current Task")
        lines.append("")
        lines.append(entry["entry"])
        lines.append("")
        if entry["files_touched"]:
            try:
                files = json.loads(entry["files_touched"])
                if files:
                    lines.append(f"Active files: {', '.join(files)}")
                    lines.append("")
            except (json.JSONDecodeError, TypeError):
                pass

    lines.append("## Architecture")
    lines.append("")
    for system in snapshot.systems:
        lines.append(f"### {system.system} ({system.file_count} files)")
        lines.append("")
        for f in system.files:
            short_path = f["path"].replace("src/", "")
            lines.append(f"- **{short_path}** -- {f['purpose']}")
        lines.append("")

    if snapshot.global_dangers or snapshot.file_dangers:
        lines.append("## Danger Zones")
        lines.append("")
        lines.append(
            "> These are invariants the codebase depends on. "
            "Violating them causes bugs that are hard to trace."
        )
        lines.append("")
        for danger in snapshot.global_dangers:
            tag = " *(human)*" if danger["added_by"] == "human" else ""
            lines.append(f"- **[GLOBAL]** {danger['description']}{tag}")
            if danger["reason"]:
                lines.append(f"  *Why: {danger['reason']}*")
        for danger in snapshot.file_dangers:
            tag = " *(human)*" if danger["added_by"] == "human" else ""
            lines.append(f"- **[{danger['scope']}]** {danger['description']}{tag}")
            if danger["reason"]:
                lines.append(f"  *Why: {danger['reason']}*")
        lines.append("")

    if snapshot.decisions:
        lines.append("## Architectural Decisions")
        lines.append("")
        lines.append(
            "> These are deliberate choices. Do not refactor them away without understanding why."
        )
        lines.append("")
        for dec in snapshot.decisions:
            scope = dec["scope"] or "Global"
            tag = " *(human)*" if dec["added_by"] == "human" else ""
            lines.append(f"**{scope}**: {dec['decision']}{tag}")
            if dec["alternatives"]:
                lines.append(f"  Rejected: {dec['alternatives']}")
            if dec["reason"]:
                lines.append(f"  Because: {dec['reason']}")
            lines.append("")

    if snapshot.recent_changes:
        lines.append("## Recent Changes")
        lines.append("")
        for change in snapshot.recent_changes:
            short_hash = change["commit_hash"][:7] if change["commit_hash"] else "manual"
            author_tag = " *(AI)*" if change["author"] == "model" else ""
            lines.append(
                f"- `{short_hash}` {change['summary']}{author_tag} -- `{change['file']}`"
            )
        lines.append("")

    lines.append("## Index Health")
    lines.append("")
    lines.append(f"- Files: {snapshot.stats.file_count} indexed")
    lines.append(f"- Functions: {snapshot.stats.function_count} indexed")
    if snapshot.stats.stale_count > 0:
        lines.append(
            f"- ⚠ {snapshot.stats.stale_count} files have stale metadata "
            f"-- run `ctx sync` to refresh"
        )
    if snapshot.stats.tainted_count > 0:
        lines.append(
            f"- ⚠ {snapshot.stats.tainted_count} functions are tainted "
            f"(dependency changed) -- run `ctx sync` to clear"
        )
    if snapshot.stats.stale_count == 0 and snapshot.stats.tainted_count == 0:
        lines.append("- ✓ Index is current")
    lines.append("")

    lines.append("## ctx Workflow")
    lines.append("")
    lines.append("This project uses ctx for automatic codebase context management.")
    lines.append("")
    lines.append("**Before editing any file:** Call `ctx_get_context(file=...)` to load")
    lines.append("current metadata, summaries, danger zones, and session state.")
    lines.append("")
    lines.append("**After editing any file:**")
    lines.append("1. `ctx_update_file(file=..., purpose=..., last_change=...)`")
    lines.append("2. `ctx_update_function(id=..., summary=...)` for each changed function")
    lines.append("3. `ctx_log_session(entry='What I did. What is next.')` to save task state")
    lines.append("")
    lines.append(
        "**Summary quality standard (15 words max, starts with verb):**"
    )
    lines.append(
        "> 'Sends leaf batch to GPU evaluator, undoes virtual loss, backpropagates values.'"
    )
    lines.append("")

    return "\n".join(lines)


def render_copilot_instructions(snapshot: ProjectSnapshot, gen_ts: str | None = None) -> str:
    ts = gen_ts or _now_ts()
    lines = [
        "# Copilot Instructions",
        TIMESTAMP_LINE.format(ts=ts),
        "",
        f"Repository: **{snapshot.repo_name}**",
        "",
    ]

    lines.append("## Modules")
    lines.append("")
    for system in snapshot.systems:
        lines.append(f"**{system.system}** ({system.file_count} files)")
        for f in system.files[:5]:
            short = f["path"].split("/")[-1]
            lines.append(f"  - `{short}`: {f['purpose']}")
        if len(system.files) > 5:
            lines.append(f"  - *(+{len(system.files) - 5} more)*")
    lines.append("")

    all_dangers = snapshot.global_dangers + snapshot.file_dangers
    if all_dangers:
        lines.append("## Critical Constraints")
        lines.append("")
        for danger in all_dangers:
            lines.append(f"- {danger['description']}")
            if danger["reason"]:
                lines.append(f"  *(Reason: {danger['reason']})*")
        lines.append("")

    if snapshot.decisions:
        lines.append("## Architectural Decisions (Do Not Refactor)")
        lines.append("")
        for dec in snapshot.decisions:
            scope = dec["scope"] or "Global"
            lines.append(f"- **{scope}**: {dec['decision']}")
        lines.append("")

    if snapshot.stats.stale_count > 0 or snapshot.stats.tainted_count > 0:
        lines.append(
            f"> ⚠ Index has {snapshot.stats.stale_count} stale files "
            f"and {snapshot.stats.tainted_count} tainted functions. Run `ctx sync`."
        )
        lines.append("")

    return "\n".join(lines)


def render_opencode_config(snapshot: ProjectSnapshot, gen_ts: str | None = None) -> str:
    ts = gen_ts or _now_ts()
    lines = [
        "# OpenCode Context",
        f"# {TIMESTAMP_LINE.format(ts=ts)}",
        "",
        f"project: {snapshot.repo_name}",
        f"indexed_files: {snapshot.stats.file_count}",
        f"indexed_functions: {snapshot.stats.function_count}",
        "",
        "systems:",
    ]
    for system in snapshot.systems:
        files_list = ", ".join(f["path"].split("/")[-1] for f in system.files[:5])
        lines.append(f"  {system.system}: {files_list}")
    lines.append("")

    if snapshot.global_dangers:
        lines.append("critical_constraints:")
        for danger in snapshot.global_dangers:
            lines.append(f"  - \"{danger['description']}\"")
        lines.append("")

    if snapshot.session_log:
        lines.append(f"current_task: \"{snapshot.session_log[0]['entry']}\"")
        lines.append("")

    lines.append("workflow:")
    lines.append("  before_edit: call ctx_get_context(file=...)")
    lines.append("  after_edit: call ctx_update_file and ctx_update_function")
    lines.append("  log_progress: call ctx_log_session")

    return "\n".join(lines)


def render_generation_timestamp(file_path: Path) -> str | None:
    """Extract the ``<!-- Generated: ... -->`` generation timestamp.

    Tolerates a leading comment prefix (``# `` in opencode.md) so every
    rendered artifact's header is freshness-detectable by ``ctx status``.
    """
    try:
        text = file_path.read_text(encoding="utf-8")
    except (IOError, OSError):
        return None

    for line in text.splitlines():
        candidate = line.strip()
        if candidate.startswith("#"):
            candidate = candidate.lstrip("#").strip()
        if candidate.startswith("<!-- Generated: ") and candidate.endswith("-->"):
            return candidate[len("<!-- Generated: "):-len(" -->")].strip()
    return None


def latest_index_timestamp(conn: sqlite3.Connection) -> str | None:
    """Most recent updated_at/created_at across all content-bearing tables.

    Drives export freshness: an output file is stale when its stored generation
    timestamp predates this value.
    """
    row = conn.execute(
        "SELECT MAX(u) FROM ("
        "SELECT MAX(updated_at) AS u FROM files "
        "UNION ALL SELECT MAX(updated_at) FROM functions "
        "UNION ALL SELECT MAX(created_at) FROM dangers "
        "UNION ALL SELECT MAX(created_at) FROM decisions)"
    ).fetchone()
    return row[0] if row else None
